/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 datacenter.gltf --transform
Author: Alex Martire (https://sketchfab.com/alexmartire)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/data-center-low-poly-59b31b45e80c484e98e1839ab1acc90b
Title: Data Center (low-poly)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/datacenter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.39, 590.1, -1600.03]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cluster_MetalCase_0.geometry} material={materials.MetalCase} />
          <mesh geometry={nodes.Cluster_Frente_0.geometry} material={materials.Frente} />
          <mesh geometry={nodes.Cluster_Verde_0.geometry} material={materials.Verde} />
          <mesh geometry={nodes.Cluster_Amarelo_0.geometry} material={materials.Amarelo} />
        </group>
        <group position={[1.92, 1790, -1700]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.LampTeto003_LampCase_0.geometry} material={materials.LampCase} />
          <mesh geometry={nodes.LampTeto003_LampTeto_0.geometry} material={materials.LampTeto} />
        </group>
        <mesh geometry={nodes.Plane_PisoPreto_0.geometry} material={materials.PisoPreto} rotation={[-Math.PI / 2, 0, 0]} scale={2200} />
        <mesh geometry={nodes.Plane001_PisoBranco_0.geometry} material={materials.PisoBranco} rotation={[-Math.PI / 2, 0, 0]} scale={2200} />
      </group>
    </group>
  )
}

useGLTF.preload('/datacenter-transformed.glb')
