/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 rip.gltf --transform
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rip-aventador-838b55ae51e348a98702ac47474ca4f4
Title: R.I.P AVENTADOR
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rip-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 0, 0.01]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.MattePaint} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Carbonne} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.010']} />
      </group>
      <group position={[0, -0.01, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={4.74}>
        <mesh geometry={nodes.Object_18.geometry} material={materials.Matte__FF070707__spec} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['plaquette_de_frein.002']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['visse.002']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Chrome_Text_Logo} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.CRBN_JANTE} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.MetalDark} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.MetalGoldenLogo} />
      </group>
      <group position={[1.65, 0.55, 2.29]} rotation={[-Math.PI / 2, 0, 0]} scale={4.74}>
        <mesh geometry={nodes.Object_38.geometry} material={materials.MetalDark} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.MetalGoldenLogo} />
      </group>
      <group position={[0.01, 0.84, 3.97]} rotation={[-2.5, 0, 0]} scale={8.73}>
        <mesh geometry={nodes.Object_41.geometry} material={materials.MetalDark} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.MetalGoldenLogo} />
      </group>
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.045']} position={[-3.38, 0.07, -1.61]} rotation={[0, -Math.PI / 2, 0]} scale={1.41} />
    </group>
  )
}

useGLTF.preload('/rip-transformed.glb')
